name: docdoc
description: "docdoc"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  build_runner: ^2.13.1
  flutter_bloc: ^9.1.1

  freezed: ^3.2.5
  freezed_annotation: ^3.1.0

  get_it: ^9.2.1

  json_serializable: ^6.13.1
  json_annotation: ^4.11.0

  dio: ^5.9.2
  retrofit: ^4.9.2
  pretty_dio_logger: ^1.4.0

  intl: ^0.20.2
  easy_localization: ^3.0.8

  flutter_native_splash: ^2.4.7

  flutter_svg: ^2.2.4

  flutter_screenutil: ^5.9.3


  cached_network_image: ^3.4.1

  shared_preferences: ^2.5.5

  flutter_secure_storage: ^10.0.0

  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
