// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvd4IEc1P8nWLWJs31r2vC5lywaElnXRU',
    appId: '1:796571880043:web:ae098282f8eb5cfc00ff2e',
    messagingSenderId: '796571880043',
    projectId: 'app-distribution-24760',
    authDomain: 'app-distribution-24760.firebaseapp.com',
    storageBucket: 'app-distribution-24760.firebasestorage.app',
    measurementId: 'G-BE10FG14SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn4CJNr6taGeL-eWJJzrjPzoMXqukkKjA',
    appId: '1:796571880043:android:ea4fc128e60f990200ff2e',
    messagingSenderId: '796571880043',
    projectId: 'app-distribution-24760',
    storageBucket: 'app-distribution-24760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArA-80zImOgoYv4DqHDCf8IbIaZ5gINsA',
    appId: '1:796571880043:ios:d1592e3a47744d7a00ff2e',
    messagingSenderId: '796571880043',
    projectId: 'app-distribution-24760',
    storageBucket: 'app-distribution-24760.firebasestorage.app',
    iosBundleId: 'com.example.docdoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArA-80zImOgoYv4DqHDCf8IbIaZ5gINsA',
    appId: '1:796571880043:ios:d1592e3a47744d7a00ff2e',
    messagingSenderId: '796571880043',
    projectId: 'app-distribution-24760',
    storageBucket: 'app-distribution-24760.firebasestorage.app',
    iosBundleId: 'com.example.docdoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvd4IEc1P8nWLWJs31r2vC5lywaElnXRU',
    appId: '1:796571880043:web:06d97cc08ac3530100ff2e',
    messagingSenderId: '796571880043',
    projectId: 'app-distribution-24760',
    authDomain: 'app-distribution-24760.firebaseapp.com',
    storageBucket: 'app-distribution-24760.firebasestorage.app',
    measurementId: 'G-3H2CSF0ZB5',
  );
}
