default_platform(:android)

platform :android do
  desc "Send APK To FireBase App-Distribution"
  lane :distribution do
      sh "flutter clean"
      sh "flutter build apk --release --flavor production -t lib/main_production.dart"
      firebase_app_distribution(
         app: ENV["FIREBASE_APP_ID"],
         firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
         testers: "yousefobid521@gmail.com",
         android_artifact_type: 'APK',
         android_artifact_path:'../build/app/outputs/flutter-apk/app-production-release.apk',
         release_notes: "Test Action In Git Hub And Send APK in the FireBase "
   )
  end
end
